### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by bborn**
Sorry for the ugly commit history, I was playing around with the right way to do this. Hopefully it works. It seems bower needs a bower.json file with a 'main' entry in order to work properly.

### CODE REVIEW

**Comment by e1himself** [comment]
Hi!

@bborn , have you tested Columns Block with bower-retrieved dependenices?

As far as I see it won't work in the current state. I see a couple of problems. Currently Sir Trevor repo cannot be used as bower dependency (neigher original, nor mine). 
1. Try to run `bower install` and you'll see it has no built javascript version in it
2. Original sources cannot be used directly as they should be browserified first. 
3. Furthermore, it has some sources removed by `ignore` configuration.

That brings us to the fact that SirTrevor bower verion is broken currently and cannot be used in any way. Therefore no need to add `bower.json` to this plugin's repo too. It would be useless.

**Comment by bborn** [comment]
Yeah, I'm able to get it to work. Here's what I had to do:

In my app's bower.json I have:

```
  "dependencies": {
    "requirejs": "~2.1",
    "sir-trevor-js": "el1himself/sir-trevor-js#master",
    "sir-trevor-columns-block": "el1himself/sir-trevor-columns-block#master"
  },
```

That pulls the right files in. Then I have to go into each of those components and build the package (`npm install && grunt build && mv build/* ./`).

Obviously there must be a better way, but I'd like to be able to use these dependencies in Rails via Bower (any tips/suggestions are welcome).

**Comment by e1himself** [comment]
I see. 
But even now I still doubt you can build bower-retrieved Sir Trevor. 
It lacks almost all of it's source files. You'll still need to clone repo by yourself to build Sir Trevor.

See [bower.json](https://github.com/madebymany/sir-trevor-js/blob/0efd48bff8e0550890b3e33eab5f724d89425dd2/bower.json) from original Sir Trevor repo:

``` javascript
{
"ignore": [
    "**/.*",
    "node_modules",
    "components",
    "src/!(blocks)", // <--- note this 
    "spec",
    "examples",
    "website",
    "BrowserRunner.html"
  ]
}
```

Therefore after `bower install` we will get this source tree:
bower

instead of this:
original

**Comment by bborn** [comment]
Yeah, good point - think it's working for me because I have sir-trevor-js linked to my local repo (using bower link), so that I could contribute my changes.

Why not just fix the bower.json in your sir-trevor-js fork?

**Comment by e1himself** [comment]
I try to stick with minimal changes to SirTrevor repo. This fork's purpose is only bringing minimal core changes to original Sir Trevor. So when (or _if_) SirTrevor team will merge core changes I could remove this repo as unneeded.

It looks like in the first place we need to suggest these changes in a separate pull requests to original Team. In any way it's better to implement them in a separate repo. Maybe I should consider inroducing a full-featured fork of SirTrevor with all build problems fixed.

**Comment by e1himself** [comment]
@bborn ,
1. I've created a separate Sir Trevor fork with a patch applied to master (it is intended to be a patched Sir Trevor replacement). See [e1himself/mr-trevor-js](https://github.com/e1himself/mr-trevor-js).
2. Also I've created a Bower shim repository to allow installing Mr. Trevor Editor (patched fork of Sir Trevor) via composer. It contains only pre-built scrips of the editor. See [e1himself/mr-trevor-js-bower](https://github.com/e1himself/mr-trevor-js-bower). Now you can install it with `bower install mr-trevor-js`.
3. And finally, I've merged your bower.json to this repo (with commits rebased to a single one) and added dependency to Mr. Trevor bower component.

Please check if bower installation is woking now.

**Comment by bborn** [comment]
Looks good! Works for me.

**Pull request closed without merging**
